"""Refactor order model

Revision ID: 343d64503323
Revises: 57e75e99b736
Create Date: 2023-03-04 03:00:46.349114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343d64503323'
down_revision = '57e75e99b736'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE skinstyle AS ENUM('air', 'century', 'shady')")
    op.execute("CREATE TYPE skinmodel AS ENUM('alex', 'steve')")
    op.execute("ALTER TYPE ordertype RENAME TO ordertype_old")
    op.execute("CREATE TYPE ordertype AS ENUM('skin', 'totem_3d', 'totem_2d')")
    op.execute("ALTER TABLE orders ALTER COLUMN order_type TYPE ordertype USING order_type::text::ordertype")
    op.execute("DROP TYPE ordertype_old")

    op.add_column('orders', sa.Column('skin_style', sa.Enum('air', 'century', 'shady', name='skinstyle'), nullable=True))
    op.add_column('orders', sa.Column('skin_model', sa.Enum('steve', 'alex', name='skinmodel'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'skin_model')
    op.drop_column('orders', 'skin_style')

    op.execute("DROP TYPE skinstyle")
    op.execute("DROP TYPE skinmodel")

    op.execute("ALTER TYPE ordertype RENAME TO ordertype_old")
    op.execute("CREATE TYPE ordertype AS ENUM('skin', 'totem_3d', 'totem_2d')")
    op.execute("ALTER TABLE orders ALTER COLUMN order_type TYPE ordertype USING order_type::text::ordertype")
    op.execute("DROP TYPE ordertype_old")
    # ### end Alembic commands ###
