"""Added ref_msgs and artists_priority

Revision ID: 48bb366ca47c
Revises: 343d64503323
Create Date: 2023-03-06 14:43:31.145151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48bb366ca47c'
down_revision = '343d64503323'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_priority',
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_priority_id'), 'artist_priority', ['id'], unique=False)
    op.create_table('ref_msgs',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ref_msgs_id'), 'ref_msgs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ref_msgs_id'), table_name='ref_msgs')
    op.drop_table('ref_msgs')
    op.drop_index(op.f('ix_artist_priority_id'), table_name='artist_priority')
    op.drop_table('artist_priority')
    # ### end Alembic commands ###
