"""add isbusy

Revision ID: 75861a2ff231
Revises: 88ba6e8f517c
Create Date: 2023-03-08 03:25:54.462908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75861a2ff231'
down_revision = '88ba6e8f517c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_busy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_busy')
    # ### end Alembic commands ###
