"""Artist_id in orders

Revision ID: a8b0d6ffb0e4
Revises: 75861a2ff231
Create Date: 2023-03-12 18:35:30.282158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b0d6ffb0e4'
down_revision = '75861a2ff231'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'artist_id')
    # ### end Alembic commands ###
