"""users, orders, artists models

Revision ID: da0fb88fceb0
Revises: 23db13fbe2e8
Create Date: 2023-03-02 13:54:51.227240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0fb88fceb0'
down_revision = '23db13fbe2e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('balance', sa.Float(), default=0, nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('order_type', sa.Enum('skin_air', 'skin_shady', 'skin_century', 'totem_3d', 'totem_2d', name='ordertype'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.alter_column('admins', 'peer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('artists', sa.Column('balance', sa.Float(), default=0, nullable=True))
    op.alter_column('artists', 'peer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'peer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('artists', 'balance')
    op.alter_column('admins', 'peer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
